name: Esegui script manualmente

on:
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa le dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installa i browser Playwright
        run: |
          playwright install

      - name: Esegui lo script
        run: python run.py
